# Generated by Django 3.2 on 2021-04-23 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('e_mail', models.EmailField(max_length=45, unique=True)),
                ('phone_num', models.CharField(max_length=12)),
                ('vk_link', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('imprint', models.ImageField(upload_to='')),
                ('shortdescription', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=1000)),
                ('problem', models.CharField(max_length=1000)),
                ('analysis', models.CharField(max_length=1000)),
                ('curator', models.CharField(max_length=45)),
                ('project', models.ManyToManyField(to='problems.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=1000)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='problems.users')),
            ],
        ),
    ]
