# Generated by Django 3.2 on 2021-04-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project',
            field=models.ManyToManyField(related_name='project', to='problems.Users'),
        ),
    ]
